### ISSUE TITLE
mate-screenshot: Option to add timestamp to filename

### ISSUE THREAD

**Issue by Taknamay** [mate-desktop/mate-utils#115]
Gnome screenshot automatically saves files with at timestamp, making it easy to order your files. I think it would be great if mate-screenshot did the same or something similar.

**Comment by mrosic** [comment]
I'm using Linux Mint 17.2 and this funcitonality was the default for Linux Mint 17.1! 
With 17.2 the timestamps are gone and there is no option to enable the timestamps in the filename. Missing it a lot.

**Comment by infirit** [comment]
@mrosic mate-screenshot never did this so please report this problem to Mint ppl.

**Comment by infirit** [comment]
Will be in the next 1.12 release.
