### ISSUE TITLE
Divide mate-utils into 5 packages 

### ISSUE THREAD

**Issue by GreenLunar** [mate-desktop/mate-utils#116]
Hello,

I am using Salix OS 14.1 (Xfce edition).

When I am marking `mate-utils` for installation, GSlapt package manager marks 4 unrelated packages (over 15MB) `libmateweather`, `mate-desktop`, `mate-menus`, `mate-panel`, which I do not need. The only dependency I needed the most is `libgtop`.

`mate-disk-usage-analyzer`, which is the only thing I need from `mate-utils`, works without the aforementioned 4 packages.
`mate-screenshot` can work even without `libgtop`.

**Comment by flexiondotorg** [comment]
Speak with the Salix package maintainers, they can split the packages if need be :-)

**Comment by GreenLunar** [comment]
I assume others who use other distributions are interested in the same thing.  I think it would be good to split it at upstream level.

**Comment by NiceandGently** [comment]
@willysr
please work on it :)

**Comment by infirit** [comment]
Splitting this is up to the distro. For MATE it means unnecessary adding work for no gain.

**Comment by GreenLunar** [comment]
Please reopen this ticket.  At least label this issue priority-low.

**Comment by NiceandGently** [comment]
for what reason?
I split mate-utlis since 2 years in subpackages for fedora......or do you compile for yourself and don't know how to spit the package for your distro?

**Comment by willysr** [comment]
You can try to contact George (Salix maintainer) for this issue as this is a packaging issue (downstream), not development issue (upstream).

i maintain MSB project for Slackware and i used this scheme as well, but so far, no one complained :)

**Comment by GreenLunar** [comment]
No, just split it upstream.  Users may not know that a search and log viewer programs etc. are available from MATE.

P.S.
```
<p>MATE is available via <em>unofficial</em> repositories for the following Linux distributions:</p>
<ul class="simple">
<li><a class="reference external" href="http://www.slackware.com">Slackware</a></li>
```

I suggest to replace http://www.slackware.com by link http://mateslackbuilds.github.io

**Comment by willysr** [comment]
As mentioned before, upstream has no intention or need to split them. It's downstream issues.

The link is correct, since it refers to Linux distribution. MSB is a project to provide MATE packages for Slackware distribution.

**Comment by GreenLunar** [comment]
> As mentioned before, upstream has no intention or need to split them. It's downstream issues.

Some of them think otherwise.

> The link is correct, since it refers to Linux distribution. MSB is a project to provide MATE packages for Slackware distribution.

Add (MATE SlackBuilds) hyperlink next to Slackware, then.

**Comment by infirit** [comment]
>Some of them think otherwise.

What do you mean, "some" in the MATE project?

>Add (MATE SlackBuilds) hyperlink next to Slackware, then

Detailed install instructions are on the [wiki](http://wiki.mate-desktop.org/download#slackware)

**Comment by willysr** [comment]
"Some of them think otherwise."
well it's not upstream's concern if they think that way

"Add (MATE SlackBuilds) hyperlink next to Slackware, then."
MSB is not a Linux distribution. The text refers to Linux distribution, so Slackware is the correct link.

**Comment by GreenLunar** [comment]
I disagree with everyone on this thread.

**Comment by mrnhmath** [comment]
I saw a discussion where people were pointing out that MATE seems "bloated" and "non-modular". Could mate-utils have a share of blame? Pinging @raveit65 @flexiondotorg @monsta

**Comment by raveit65** [comment]
This can be done by distro maintainer. An example what i do for fedora.
http://pkgs.fedoraproject.org/cgit/rpms/mate-utils.git/tree/mate-utils.spec#n73
And i am against to split it here because it is my rare free time about you're speaking :P 
Splitting a package in single packages means more work for releasing, maintaining.etc.
