### ISSUE TITLE
mate-system-log and Ctrl-W

### ISSUE THREAD

**Issue by ofbgh** [mate-desktop/mate-utils#119]
Ctrl-W is toolbar-menu>File>Close

When I use it, the log being viewed vanishes from the view window, and from the sidebar list. Then that log remains vanished, even after reboots...

I believe this "Close" function is not meant to be so enthusiastic. I confirmed the behavior on the LiveISO of my distro as well.

3.16.0-38-generic x86_64 (64 bit) 
MATE 1.10.0
Linux Mint 17.2 Rafaela

EDIT -- okay,  Mint forum member GeneBenson has shown me that "Closed" logs can be retrieved via File>Open, and I agree with his suggestion that "Remove" would be a better term for the Ctrl-W action.

The problem is the user is faced with a pre-populated sidebar. Because of that, it is not obvious a "Close" action will remove a log entirely from the app. Otherwise, I do now see why the original devs chose to use Close and Open in the way they did.

**Comment by monsta** [comment]
So... what do you want to change there after all? :smile:

**Comment by ofbgh** [comment]
Hiya

How else do I phrase it for you... how about:" Unexpected behavior surprises users, and then has a non-obvious reset to original state." ; )

I'm treating this as a bug report, not a feature request. Devs are great at solving problems -- they just need to be advised a problem exists at some level or for some users. My suggestion of "Remove" above is only to help illustrate the perceived issue.

Besides, this one's not clear from my view in user-land. The way mate-system-log operates suggest that its own developers see it as an unpopulated item. Then "Open"&"Close" make perfect sense. It's the pre-population of the sidelist before the user gets it, that makes those behaviors a surprise/confusion for the user. That pre-population may be by a later team, possibly in MATE, possibly in the distro.

So it could be a little fun figuring out how to stop this from biting new users of the Log Viewer.

**Comment by infirit** [comment]
``File->Close`` closes the file
``File->Quit`` quits the program

I don't see how this can confuse anyone.

**Comment by infirit** [comment]
I looked around my desktop and this behaviour is seen all over the place. Thunderbird, pluma, libreoffice, filemanagers etc. I don't see any reason why to change this.

**Comment by ofbgh** [comment]
Oh - It confuses not because it closes a file, but because it is not clear to the user that the item was a opened file, rather than a menu item.

When you close it, it disappears not only from the view panel, but also from the side panel options.

Since the user did not populate the side panel, it is not obvious to the user that those are a collection of opened files. And so it is not obvious how to retrieve the entry that is now missing.

That's how this is non-standard, compared to Close in every other app I can think of too.
