### ISSUE TITLE
mate-screenshot: Compiz captures highlight rectangle

### ISSUE THREAD

**Issue by lah7** [mate-desktop/mate-utils#128]
Unfortunately, when using `mate-screenshot` to capture an area of the screen under Compiz, the "highlight rectangle" is also captured along too, as the animation hasn't finished.

Initially reported on Launchpad for Ubuntu MATE, with two screenshots:
https://bugs.launchpad.net/ubuntu-mate/+bug/1503326
https://bugs.launchpad.net/ubuntu-mate/+bug/1503326/+attachment/4486120/+files/Screenshot-Example1-Dialog.png
https://bugs.launchpad.net/ubuntu-mate/+bug/1503326/+attachment/4486121/+files/Screenshot-Example2-Image.png

This results in a screenshot with the highlight partially or fully captured.

Possible workarounds:
1) Ability to use the parameters `--delay` and `--area` simultaneously (as well as via GUI), so that there can be a user-specified delay of x seconds after the area is selected.
2) An option to alternatively highlight the area for capturing that doesn't involve the highlighted, for instance, an 1px offset border.
3) Detect if `compiz` is running, and delay the capture by a second.

**Comment by lah7** [comment]
Well, since upgrading to Ubuntu MATE 15.10 (now using `mate-utils 1.10.3-.1` and `compiz 0.9.12.2`), the highlight disappears in time before `mate-screenshot` captures the area of the screen. Very, **very** rare chance it happens now.

I'm not sure if this was addressed between versions 1.8 or 1.10, or if this was because the Compiz profile had been modified to increase the "Close Animation" duration value.

This may be more of a feature request now, since using `--delay` and `--area` can be useful in some cases, and a workaround if this happens again.

**Comment by monsta** [comment]
Sounds like an issue in Compiz itself. Does it still happen in MATE 1.12?

**Comment by lah7** [comment]
No, this doesn't happen anymore. Something must have mysteriously been corrected in newer versions.
