### ISSUE TITLE
Adding Kazam instead mate-screenshot (in mate-utils)

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-utils#129]
Kazam (https://apps.ubuntu.com/cat/applications/kazam/) makes exactly the same things than mate-screenshot but with the video capture too.
It could be interesting to remove mate-screenshot and to add Kazam.
![capture](https://cloud.githubusercontent.com/assets/3955499/11448704/f8dfdbc6-955d-11e5-9231-a6621dfb3d68.png)

**Comment by monsta** [comment]
Sure, feel free to replace m-s with kazam in your system :smile:

**Comment by Petrouchka** [comment]
Did you closed this bug report because Kazam will be added in the next release of MATE-DESKTOP ? I didn't made this bug report only to know if I can use or not Kazam, I KNOW I can use it.
