### ISSUE TITLE
Command mate-screenshot -ai does not disable other options

### ISSUE THREAD

**Issue by aykevl** [mate-desktop/mate-utils#133]
When running `mate-screenshot -ai`, it doesn't disable (gray out) the other options like delay and pointer.
I usually run `mate-screenshot -ai` as a shorthand to take screenshot of part of the screen. This time I wanted to do it after a timeout, but found out mate-screenshot doesn't support that. The option wasn't grayed out, though, because I started mate-screenshot via the command line.

To reproduce, just run `mate-screenshot -ai`, and see that options aren't disabled.

**Comment by raveit65** [comment]
Hmm,
-i stands for --interactive.
If you don't want to change the options use simply 'mate-screenshot -a'.
--interactive does not mean to disable the options.

**Comment by aykevl** [comment]
The point is that 'area' mode does not support options like delay but still has them enabled (not grayed out). When selecting 'area' after another mode (like whole screen) was selected the options get disabled.

**Comment by raveit65** [comment]
Ok, got it
Using -ai shows the options from whole screen (only using -i).
Switching to another option and back in gui shows the right options for -ai.
-wi shows the right options for window mode and
-i shows the right options for whole screen mode.
