### ISSUE TITLE
GTK3.19: must configure w/ --enable-maintainer-flags=no

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-utils#135]
At least in gtk 3.19 if not earlier versions of gtk3, the "--enable-maintainer-flags=no" must be selected at configuration or the default CFLAGS include -werror and the build stops on deprecated gtk widgets. Not sure if this is due to newly deprecated widgets or a change in the default configuration

**Comment by raveit65** [comment]
I guess this is a debug setting during development phase of gtk+.
I hope those guys will disable this for stable releases.

**Comment by lukefromdc** [comment]
Strangely it's only that one package. Mate-media used to require an
--enable-deprecated  flag back in the 1.10 days, sometime during the 
summer the need for that ended.

**Comment by raveit65** [comment]
This is independent from gtk+ version, it is because we use a dev version (unstable) 1.13.
I recall this that we had the same prob with mate-terminal.

**Comment by lukefromdc** [comment]
OK, this is now fixed as of Jan 25 with the removal of -werror from the maintainer flags. Default build now completes. Unfortunately we have a new issue: mate-dictionary is non-reponsive in GTK 3.19. 
(mate-dictionary:1530): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Mostly works in 3.18(except selecting "new), rolled back to test the dev-dictionary branch, those changes worked fine with it.

**Comment by monsta** [comment]
I guess this can be closed as https://github.com/mate-desktop/mate-utils/issues/136 is opened about a new problem?

**Comment by lukefromdc** [comment]
Yes as this was fixed quite a while ago when -werror was taken out of the maintainer flags. A test build with gtk3.19 and no configure options to disable maintainer mode just went fine
