### ISSUE TITLE
mate-dictionary: entire window nonresponsive with GTK 3.19.7

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-utils#136]
May be related also getting a nonresponsive window if you select "new" from the menu in GTK 3.18. In gtk3.19 only I got this error which may or may not be related to this:

(mate-dictionary:1530): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

Opened mate-dictionary from the panel run dialog, had to use the panel force-quit applet to close it

**Comment by lukefromdc** [comment]
This is unrelated to #135, a build today went fine but on trying to run mate-dictionary from it I still got 
the same error as listed above and a nonresponsive window that does not even respond to the Compiz window close button

**Comment by monsta** [comment]
Yes, I see a lot of such messages with 3.18 when I use "New" menu item...

**Comment by monsta** [comment]
Ok, fixed the problem in 3.18 in https://github.com/mate-desktop/mate-utils/commit/d746e6200476b98b07f23d80268a992508e32477. Please check if it fixes 3.19 problem...

**Comment by lukefromdc** [comment]
FIxed in gtk3.19 too, opened and could look up words without generating errors. Good enough to use as it is now.

There are other errors from trying to use the sidebar or statusbar, and an error in terminal when the window is closed. These are in GTK 3.19.11 and probably are separate issues:

Closing gets:

```
(mate-dictionary:29227): GLib-GObject-WARNING **: /build/glib2.0-2.46.2/./gobject/gsignal.c:2634: instance '0x1e7f330' has no handler with id '1417'

(mate-dictionary:29227): Gdk-CRITICAL **: gdk_frame_clock_idle_end_updating: assertion 'priv->updating_count > 0' failed

```

Trying to select "statusbar" in view no response, no error text.

Trying to select sidebar in "view" gets errors below and no sidebar but main window still works:

```
(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node separator owner GtkPaned)

(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node separator owner GtkPaned)

(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node separator owner GtkPaned)

(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node separator owner GtkPaned)

(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node separator owner GtkPaned)

(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node separator owner GtkPaned)

(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node separator owner GtkPaned)

(mate-dictionary:29606): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (n
```

**Comment by monsta** [comment]
Wow. I don't get any of these with 3.18...

**Comment by raveit65** [comment]
> Wow. I don't get any of these with 3.18...

...time to install a VM with gtk+-3.19.x.
There are distros which will use latest gtk+ in a few weeks.

**Comment by lukefromdc** [comment]
Closing this as it has been fixed
