### ISSUE TITLE
Can't make a shortcut of `mate-screenshot -a`

### ISSUE THREAD

**Issue by aug-riedinger** [mate-desktop/mate-utils#137]
When I type `mate-screenshot -a` in the terminal, it works as expected: the cross appears so I can select the area I want to screen.

But if I add this as a custom shortcut (in debian), it falls back to the `mate-screenshot` behavior.

I tried to shortcut `eval 'mate-screenshot -a'` or made a custom script out of it, the same happens.

But if I set `mate-screenshot -i` it works fine.

There must be some kind of fallback behavior when called from a shortcut, which - it would be awesome - needs a fix!

Let me know if I can help.

**Comment by monsta** [comment]
Already reported at https://github.com/mate-desktop/mate-utils/issues/37
