### ISSUE TITLE
Gtk3.21-mate-dictionary segfault

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-utils#144]
Another (deprecated) GtkStyle issue, never removed from or replaced in Gtk3 builds. 
https://github.com/mate-desktop/mate-utils/pull/143
Fixes this, and as in Caja it does not stop mate-dictionary's window from following the theme. All the MATE themes tested plus Adwaita and UbuntuStudio_Legacy, no adverse effects observed.  Tested this build (over 3.21 with GtkStyle disabled in gdict-window.c) in Gtk 3.16 as well, no adverse effects observed.

Probably we can disable this in all GTK3 builds, but I've limited it to Gtk 3.21 for the sake of avoiding regressions for now. Still, this is deprecated so if further tests show it's doing nothing or not needed, we should get rid of it in all the GTK3 builds.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-utils/pull/146  is a better way to fix this, as the exact command within the function in question was gtk_widget_realize and I tracked that down switched it in GTK 3.21 to gtk_widget_show which does the same thing implicitly and does not segfault

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/mate-utils/commit/f832d9e9327f41ac653a7623e4f51d5139a03e1d
