### ISSUE TITLE
mate-screenshot does not allow to copy screenshot to clipboard by commandline argument

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-utils#160]
Steps to reproduce:
1. Launch mate-screenshot -h from terminal
2. Ensure that there is no option to copy screenshot to clipboard from commandline.

Expected results:
User is able to copy screenshot to clipboard as with "gnome-screenshot -c".

Actual results:
User can't to copy screenshot to clipboard from commandline.

I reported this bug from Ubuntu 16.04 on Launchpad (see [bug 1615740](https://bugs.launchpad.net/bugs/1615740)).
##

**Comment by orschiro** [comment]
Indeed, it would be great if the following was possible:

`$ mate-screenshot -ac`

**Comment by MarioMey** [comment]
I entered in this page to suggest the same. More specifically, what @orschiro said: capture area - copy to clipboard.

+1 for this feature!

**Comment by tamplan** [comment]
This should be closed?

**Comment by N0rbert** [comment]
Tested on Ubuntu MATE 20.04 LTS with MATE 1.24.0:

* `mate-screenshot -c` - works
* `mate-screenshot -a -c` - works
* `mate-screenshot -w -c` - works
