### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by edgarjaviertec** [mate-desktop/mate-utils#167]
edgar@macmini:~$ mate-screenshot --interactive
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault (core dumped)

**Comment by raveit65** [comment]
No version, no distro version....close.

**Comment by monsta** [comment]
Probably the same as https://github.com/mate-desktop/mate-utils/issues/166, if it's Spanish or Italian locale
