### ISSUE TITLE
Search Options

### ISSUE THREAD

**Issue by caltrop2075** [mate-desktop/mate-utils#181]
#### Expected behaviour
find text in
a date, not an integer

#### Actual behaviour
contains text does not appear to function
especially with system files
even when run as root/superuser

have to have calculator to figure dates

#### Steps to reproduce the behaviour
use search tool

#### MATE general version
MATE 1.18.0

#### Package version
unknown

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Link to downstream report of your Distribution
none

**Comment by mbkma** [comment]
More information needed.

**Comment by caltrop2075** [comment]
WOW!

this is for Mint Mate 18.1

I'm in Mint Mate 20.1 and two computers later

I don't even remember the details of this issue from FOUR years ago

**Comment by mbkma** [comment]
Yes, do you still have the issue?

**Comment by mbkma** [comment]
If you still have the issue it can be reopened.
