### ISSUE TITLE
Add "copy to clipboard" (-c) option to mate-screenshot 

### ISSUE THREAD

**Issue by stuartlangridge** [mate-desktop/mate-utils#182]
#### Expected behaviour
It is possible to use mate-screenshot to take a screenshot and copy it to the clipboard without having to click "Copy to clipboard" in the popup dialog.

#### Actual behaviour
This is currently not possible.
The easiest way to do this would be to add a -c option to mate-screenshot which would copy the taken screenshot (whether area, window, or whatever) to the clipboard automatically without showing the popup. This could then be bound to a shortcut key.

#### MATE general version
1.12.1

#### Package version
1.12.0 (I think)

#### Linux Distribution
Ubuntu MATE 16.04

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu-mate/+bug/1739008

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-utils/issues/160
