### ISSUE TITLE
Please install .appdata.xml files to correct metainfo location

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-utils#188]
In Debian, the .appdata.xml (apspstream) file goes into /usr/share/metainfo.

See here for the workaround, I currently have in debian/rules:
https://anonscm.debian.org/cgit/pkg-mate/mate-utils.git/commit/?id=4d2388c193cdcd916adf7080ecc2d38c360786d9

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/mate-utils/commit/846b61f8d2e73178895024a6e29b48fb9a392947, picked to 1.20 branch in https://github.com/mate-desktop/mate-utils/commit/a18324570b5274a988a66724a48a83ac119e2934.
