### ISSUE TITLE
Disk Usage Analyzer fails to open Caja

### ISSUE THREAD

**Issue by igorsantos07** [mate-desktop/mate-utils#195]
From my understanding, the application should know what's my default explorer. I have no idea how to manually configure this, and there's no option to set that on the app preferences.

#### Expected behaviour
Disk Usage Analyzer (DUA, for short) should open Caja with the selected folder.

#### Actual behaviour
>Could not open folder "xyz"
>There is no installed viewer capable of displaying the folder.

#### Steps to reproduce the behaviour
1. Run the analyzer.
2. right-click some folder.
3. select "open folder"

#### MATE general version
Mate 1.14.1

#### Package version
1.14.1

#### Linux Distribution
Linux Mint 18 Sarah

#### Link to downstream report of your Distribution
Sorry, how do I get this?

**Comment by monsta** [comment]
We don't support 1.14 release now, it's too old, and our team is small.
Please update to a newer Mint release.
