### ISSUE TITLE
Failed to pull translations from transifex (master branch)

### ISSUE THREAD

**Issue by rbuj** [mate-desktop/mate-utils#202]
Translations can not be pulled from transifex using the current .tx/config.
Can only pull translations for mate-utils and they have an incorrect charset ("charset=CHARSET").

Pulling translations for Catalan (ca) language:

$ tx pull -l ca -f
tx INFO: Pulling translations for resource MATE.master--mate-utils (source: po/mate-utils.pot)
tx WARNING:  -> ca: po/ca.po
tx ERROR: Not Found
tx ERROR: Not Found
tx ERROR: Resource MATE.master--mate-disk-usage-analyzer doesn't exist on the server.
tx ERROR: Not Found
tx ERROR: Not Found
tx ERROR: Resource MATE.master--mate-search-tool doesn't exist on the server.
tx ERROR: Not Found
tx ERROR: Not Found
tx ERROR: Resource MATE.master--mate-system-log doesn't exist on the server.
tx ERROR: Not Found
tx ERROR: Not Found
tx ERROR: Resource MATE.master--mate-dictionary doesn't exist on the server.
tx INFO: Done.

$ git diff po/ca.po
...
-"Content-Type: text/plain; charset=UTF-8\n"
+"Content-Type: text/plain; charset=CHARSET\n"
...

**Comment by raveit65** [comment]
There is a known issue with transifex (report is filed out since januar 2018) , do by hand
`sed -i 's/charset=CHARSET/charset=UTF-8/g' po/*.po`

**Comment by raveit65** [comment]
I updated tx config.

**Comment by raveit65** [comment]
I did a typo in resource-slug name which is fixed now.
Try again please.
```
[rave@mother mate-utils-dist]$ tx pull -l ca -f
tx INFO: Pulling translations for resource MATE.1-20--mate-utils (source: po/mate-utils.pot)
tx WARNING:  -> ca: po/ca.po
tx INFO: Pulling translations for resource MATE.1-20--mate-disk-usage-analyzer (source: baobab/mate-disk-usage-analyzer.pot)
tx WARNING:  -> ca: baobab/help/ca/ca.po
tx INFO: Pulling translations for resource MATE.1-20--mate-search-tool (source: gsearchtool/mate-search-tool.pot)
tx WARNING:  -> ca: gsearchtool/help/ca/ca.po
tx INFO: Pulling translations for resource MATE.1-20--mate-system-log (source: logview/mate-system-log.pot)
tx WARNING:  -> ca: logview/help/ca/ca.po
tx INFO: Pulling translations for resource MATE.1-20--mate-dictionary (source: mate-dictionary/mate-dictionary.pot)
tx WARNING:  -> ca: mate-dictionary/help/ca/ca.po
tx INFO: Done.
```
I hope i didn't broke translations.
Thanks for reporting the issue.
