### ISSUE TITLE
MATE Dictionary should allow user to change font size in view mode

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-utils#222]
#### Expected behaviour
MATE Dictionary allows user to change font size in view mode.

#### Actual behaviour
MATE Dictionary allows user to change font size only in print mode, but not in view mode.

#### Steps to reproduce the behaviour
1. Open MATE Dictionary
2. Try to change font size in view mode

#### MATE general version
1.20.4

#### Package version
1.20.2

#### Linux Distribution
Ubuntu MATE 19.04 beta

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/mate-utils/+bug/1822431

**Comment by vkareh** [comment]
hmmm... in looking at this, if you modify your "Document font" on the Appearances app, you get that font in the dictionary, which is as it should be, in my opinion.

![document-font-10](https://user-images.githubusercontent.com/259780/55822057-7954a580-5b07-11e9-934a-434bc3b93214.png)
![document-font-18](https://user-images.githubusercontent.com/259780/55822058-7954a580-5b07-11e9-9e92-b01ce21750a8.png)
