### ISSUE TITLE
[configure option for compiling mate-utils] make inkscape optional (for mate-utils-1.22.2 or later)

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/mate-utils#223]
Hello mate-desktop developers,

Today I tried to compile mate-utils from source:

https://pub.mate-desktop.org/releases/1.22/mate-utils-1.22.1.tar.xz

This was the URL I was using.

I can not get past the configure stage. The configure stage, with
a classical ./configure --prefix=/usr, reports this **error**:

checking for glib-genmarshal... /System/Index/bin//glib-genmarshal
checking for glib-mkenums... /System/Index/bin//glib-mkenums
checking for rsvg-convert... /System/Index/bin//rsvg-convert
checking for inkscape... no
**configure: error: could not locate inkscape**

I can not get inkscape to compile on my current setup due to another
problem, so I would like to suggest to make inkscape optional, unless
it is really mandatory. 

I looked at the README and found no mention of inkscape:

        intltool                 >= 0.50.1
        mate-common              >= 1.10.0
        glib                     >= 2.36.0
        gio                      >= 2.36.0
        gtk+                     >= 3.14.0
        libmate-panel-applet     >= 1.17.0
        libgtop                  >= 2.12.0
        libcanberra-gtk          >= 0.4

I assume that inkscape is probably only necessary for e. g.
mate-screenshot or something like that; but I am fine with
getting the other things to compile if that would be possible.

Right now I can not get anything to compile due to inkscape
being checked and not found.

I would like to suggest an option:

    --disable-inkscape

And perhaps a notification on the commandline, that this
will prevent installing xyz or whatever depends on inkscape
(although I can not imagine too much to depend on inkscape; 
to be honest, it confuses me that there is a dependency on
inkscape. It seems a bit counter-intuitive to me. Has this been
added recently? I could swear I could compile mate-utils,
the version before, just fine without inkscape. But anyway,
I am just reporting the problem - I am sure an appropriate
course can be picked by the mate-desktop team. Thanks
for a great DE!)

**Comment by sc0w** [comment]
the dependency was added with https://github.com/mate-desktop/mate-utils/pull/220

**Comment by lukefromdc** [comment]
I never noticed that as I have inkscape installed for other reasons. Assuming
we are already shipping the remade icons (but allowing them to be regenerated)
there is no way we should have inkscape as even a build dependency unless it
can be turned off. It is quite a large program and download.

**Comment by Aerdan** [comment]
Is there any particular reason we need inkscape *specifically* for converting to PNG? `librsvg` (which is already a dependency) includes the `rsvg-convert` command, which supports converting SVGs to PNG format.

**Comment by raveit65** [comment]
@rbuj ping

**Comment by RecklessProcedure** [comment]
Thank You! I was about to mention this. This would also affect Linux From Scratch systems, where desktop applications typically aren't built until after the desktop and supporting utilities are installed.
