### ISSUE TITLE
Screenshot of a window in 1.24.0

### ISSUE THREAD

**Issue by g92k** [mate-desktop/mate-utils#266]
When grabbing a screenshot of a window 10 pixels or so around all sides of the window are also captured.  I build from source.  I don't believe this was the behavior in 1.22.x.

**Comment by rbuj** [comment]
Try to disable compositing, i.e. uncheck "Enable software compositing window manager".

![VirtualBox_Manjaro 19_04_03_2020_09_50_47](https://user-images.githubusercontent.com/10171411/75861442-b00d6b80-5dfd-11ea-84a4-a8a0008b09f6.png)

**Comment by raveit65** [comment]
WTF, closing because of template ignored and already reported.
https://github.com/mate-desktop/mate-utils/issues/236
