### ISSUE TITLE
mate-screenshot: need help to make changes on code

### ISSUE THREAD

**Issue by tamplan** [mate-desktop/mate-utils#296]
Hi,

I need informations about large codes in mate-scrrenshot in terms of git commits:

- move functions between existing files
- move functions in new files
- change global variables to new struct
- change #define to enum
- ...
I read the actual gnome-screenshot source code I find it more readable.

How can i do these changes in terms of git commits?

If I begin to group global variables in new struct, I need to change functions' prototype too.
Functinons `load_config` and `save_config` should be moved in dedicated file, but `get_desktop_dir` function called need to be moved to in `screenshot-save.c`.

I have made yet changes in my local repository, can i purpose you as PR for you can see the changes?
I know the big change is only in one commit this is why i open this issue to discuss about this subject.

Thanks for advance!

**Comment by mbkma** [comment]
Yes, backporting appropriate commits form https://github.com/GNOME/gnome-screenshot is a good starting point. Just open a PR and we can discuss the changes.
