### ISSUE TITLE
"gsearchtool: avoid deprecated GtkImageMenuItem" commit breaks "Open with..." functionality

### ISSUE THREAD

**Issue by L-U-T-i** [mate-desktop/mate-utils#298]
"Open with" a listed application shall open the file found through "MATE Search Tool" with that application. That worked well on my system (CentOS 8) until ["gsearchtool: avoid deprecated GtkImageMenuItem" commit](https://github.com/mate-desktop/mate-utils/commit/56ffa520f030b125c465116f816a7fa6a94596a9) (March 15 2020).

Since that commit, the list of applications seem to be shifted for 1 position (clicking the first application on the menu actually opens the file with the last listed application, clicking the first application of "Open with..." submenu actually opens the file with the first application - the one listed above the submenu - etc.).

#### Linux Distribution: CentOS 8
(rebuilt from Fedora 32 SRPM)

**Comment by sc0w** [comment]
screenshots with "expected behavior" and "actual behavior" please?

**Comment by L-U-T-i** [comment]
How exactly shall I make a screenshot showing what I've clicked and what has been opened as a result of that?

**Comment by raveit65** [comment]
Use a timer with the screenshot.

**Comment by L-U-T-i** [comment]
Thanks for a tip, @raveit65. I hope you can figure out the problem also without the screenshots though...

Anyway, attached patch seems to resolve the issue.
[mate-utils-gsearchtool-open-with-fix-patch.zip](https://github.com/mate-desktop/mate-utils/files/4889601/mate-utils-gsearchtool-open-with-fix-patch.zip)

**Comment by sc0w** [comment]
@raveit65 

![2020-07-08_11-49](https://user-images.githubusercontent.com/7734191/86904673-543b5200-c111-11ea-9222-d48af4509111.png)

open with eom it is opened with firefox instead here

@L-U-T-i your fix works, thanks, I will open new PR

**Comment by raveit65** [comment]
> open with eom it is opened with firefox instead here

...crazy mimetype world.
