### ISSUE TITLE
mate-screenshot and capturing window shadows

### ISSUE THREAD

**Issue by LiamDawe** [mate-desktop/mate-utils#305]
Hi, so this might not be a bug but more of a feature request.

When on MATE with Marco set to the Adaptive Compositor, the screenshot tool is pretty useless at just capturing windows. It tries to capture the shadow added as part of it, which ends up giving you a shot of the window + a big box of your background around it. This behaviour is obviously not ideal.

What can we do about it?

**Comment by LiamDawe** [comment]
Examples with compositor off:
https://imgur.com/a/GrKCYPm

Compositor on:
https://imgur.com/a/nUr5aQ5

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-utils/issues/236
