### ISSUE TITLE
NEWS file of mate-utils has the content of mate-notification-daemon NEWS file.

### ISSUE THREAD

**Issue by darkshram** [mate-desktop/mate-utils#318]
While peeking the changes for the 1.26.0 release, noted NEWS file has the content mate-notification-daemon NEWS file.

**Comment by raveit65** [comment]
No, commit history is fine , only naming is wrong for some reasons.
Will be fixed with next release.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-utils/commit/3d70c8ec7b5b3847fe906974dc178d03a05bdaf7
