### ISSUE TITLE
mate-screenshot dialog crashes

### ISSUE THREAD

**Issue by spartanhooah** [mate-desktop/mate-utils#357]
#### Expected behaviour
I can take and save a screenshot when hitting the PrtSc key.

#### Actual behaviour
A "Save Screenshot" window opens with the screenshot, but there's an error dialog in front. It says
"Unable to save the screenshot to disk:

Fatal error in PNG image file: Write Error"

If I click the OK button on the error dialog, both it and the "Save Screenshot" window close. If I alt-tab, then the error dialog goes away, but the "Save Screenshot" window remains, although I can't interact with it. If I hit Esc on that window in this state, it will close.

#### Steps to reproduce the behavior
Hit the PrtSc key

#### MATE general version
1.26.2

#### Package version
I don't know what package this is. The Screenshot application seems to work fine, but it's not bound to PrtSc.

#### Linux Distribution
Fedora 37

#### Link to bugreport of your Distribution (requirement)
I don't know what this means.

**Comment by raveit65** [comment]
Hmm, the print key does nothing on my f38 box with =>mate-1.27 weird.....

**Comment by raveit65** [comment]
But i do not get your error dialog.

**Comment by spartanhooah** [comment]
PrtSc is the Print Screen keyboard key on my laptop. I guess it's not always the same; my external keyboard has PrtScn.

**Comment by raveit65** [comment]
The command was disabled at my box for some reasons. Now the print button works and i can save the screenshot.
Whats the out put of this command?
`gsettings get org.mate.screenshot last-save-directory`
Does it link to a valid directory?

**Comment by spartanhooah** [comment]
The output is `''`.

**Comment by raveit65** [comment]
Try set a valid dir, eg. `gsettings set org.mate.screenshot last-save-directory 'file:///media/Run-Progs/Schreibtisch'` (this is mine.

**Comment by spartanhooah** [comment]
I set the value as `file:///home/spartanhooah/Downloads` but the error still happens.

**Comment by raveit65** [comment]
And the gsettings get command shows the new dir?

**Comment by spartanhooah** [comment]
Yes.

**Comment by raveit65** [comment]
Does it happen when you use `mate-screenshot -i ` from terminal?

Ok, i need to boot a f37 box and i will try to reproduce the issue

**Comment by spartanhooah** [comment]
Yes, `mate-screenshot 1` has the same problem.

**Comment by raveit65** [comment]
Was there an update with `libpng` package in f37?

**Comment by spartanhooah** [comment]
`dnf history list libpng` only provides one line, from November 2022.

**Comment by raveit65** [comment]
Or any other package which can be related?
I guess mate-screenhot was working when you installed the system, or you can recall last time when it was working. 
It must be a reason that it stops working from one of the other day.

**Comment by spartanhooah** [comment]
I actually haven't tried to use it until today, so I have no idea if it used to work.

**Comment by raveit65** [comment]
In an updated f37 VM `mate-screenshot -i` and saving the screenshot works fine.

**Comment by spartanhooah** [comment]
Huh. I wonder what else could be interfering.

**Comment by raveit65** [comment]
Maybe add a new user account and try it there. Sometimes something in home dir can be caused such an issue.

**Comment by spartanhooah** [comment]
A new user has the same issue.

**Comment by raveit65** [comment]
What graphic card are you using?

**Comment by spartanhooah** [comment]
Intel HD Graphics 4400 (integrated)

**Comment by raveit65** [comment]
Do you have another box with different grahics?
I am using amd Ryzen 5000 (integrated), But i don't think that this can cause the issue.
But i do not have another ideas.
Can you edit report header please?
It has nothing to do with using a keyboard command.

**Comment by spartanhooah** [comment]
Title updated. I can try later today with a live USB, if I have time. Nothing else with Fedora actually installed, currently.

**Comment by spartanhooah** [comment]
I couldn't find a quick way to download the live installer for Fedora 37, so I updated my laptop to 38, and now the behavior is fixed.
