### ISSUE TITLE
mate-dictioinary: spanish dict server does not work

### ISSUE THREAD

**Issue by ftoledo** [mate-desktop/mate-utils#96]
The default spanish server es.dict.org do not work:

Error al obtener la definición
Falló la búsqueda del host «es.dict.org»: Error desconocido

**Comment by NiceandGently** [comment]
@ftoledo 
Do you know a new spanish dic server address as repacement?

**Comment by ftoledo** [comment]
@NiceandGently sorry, i think that is not running spanish server at this time.
maybe the dict.org wiki o server list can be useful to use another server?

http://www.dict.org/w/servers/start
https://servers.freedict.org/index.php

**Comment by NiceandGently** [comment]
i found only
http://www.spanishdict.com/translation
https://enes.dict.cc/
