### ISSUE TITLE
Screenshot 'select area to grab' includes highlight color

### ISSUE THREAD

**Issue by sanderboom** [mate-desktop/mate-utils#99]
When taking a screenshot by selecting an area to grab, often, but not always, the screenshot includes the overlay/highlight color that the tool draws to indicate what area was selected and will be included in the screenshot.

![image](https://cloud.githubusercontent.com/assets/5956570/7898686/190e58f8-0708-11e5-81d7-b718c41010b1.png)

**Comment by monsta** [comment]
Does it still happen in 1.10?

**Comment by sanderboom** [comment]
Gave it a try, no problems so far. Seems fixed!

**Comment by monsta** [comment]
Cool, now you can close this issue :smile:

**Comment by sanderboom** [comment]
Sure ;)
Thanks!
